# Generated by Django 3.2 on 2021-05-01 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='publish_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 17, 42, 39, 727393, tzinfo=utc)),
        ),
    ]
