# Generated by Django 3.2 on 2021-05-01 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adsAPI', '0002_ads_publish_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='publish_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
