# Generated by Django 3.2 on 2021-05-26 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 15, 41, 38, 33538)),
        ),
    ]
