# Generated by Django 3.2 on 2021-06-12 07:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0006_alter_chat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 11, 40, 15, 769283)),
        ),
        migrations.CreateModel(
            name='fk_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('many', models.ManyToManyField(related_name='fffs', to='chatAPI.chat')),
                ('one', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatAPI.chat')),
            ],
        ),
    ]
