# Generated by Django 3.2 on 2021-06-14 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0008_auto_20210612_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 17, 14, 20, 718191)),
        ),
    ]
